### ISSUE TITLE
OrgScore - 2.5.2.1 - Enable Gatekeeper

### ISSUE THREAD

**Issue by cbruce2** [mvdbent/CIS-Script#12]
Hello,
It appears OrgScore 2.5.2.1 that references Gatekeeper is missing.  Please advise if you will be adding.

Thank you !

**Comment by reuven-cohen** [comment]
I've created an entry for 2.5.2.1 although its a work in progress.
https://github.com/reuven-cohen/CIS-Script/blob/dev/Fragments/OrgScores/OrgScore2_5_2_1.sh

**Comment by mvdbent** [comment]
Thnx @reuven-cohen added this to the project [link](https://github.com/mvdbent/CIS-Script/commit/23ceb0dbe152a48fd736c0569f2999298e05cb2a)
