### ISSUE TITLE
custom schema issue 2.4.11

### ISSUE THREAD

**Issue by PhantomPhixer** [mvdbent/CIS-Script#14]
In the jamf custom schema airdrop is missing.
Airdrop disable is 2.4.11 in the script but the custom schema has:
```
OrgScore2_4_11": {
            "type": "boolean",
            "title": "2.4.11 Disable Media Sharing (Automated)",
            "description": "This boolean is true or false.",
            "default": "false"
```
which in the script is 2.4.12

**Comment by chrisleduc** [comment]
I found that the sample json file provided is not up to date at all. You should instead run:
`Assemble.sh -j` which will create the Custom Schema based on the fragments and make sure it is always 100% accurate.

Do not use the current pre-compiled json file as it has many many more issues than just this one.
