### ISSUE TITLE
2.4.11 airdrop check on bigsur

### ISSUE THREAD

**Issue by PhantomPhixer** [mvdbent/CIS-Script#15]
There are two ways of setting airdrop off, applicationaccess and network browser.
The script checks for the networkbrowser setting for macOS12 only and uses applicationaccess for anything else.

network browser works ok as a setting on bigsur - in my testing anyway - so should also be tested on this version.

**Comment by mvdbent** [comment]
this was already fixed by @motionbug, thnx for bringing this to attention
