### ISSUE TITLE
jamf custom schema mismatch

### ISSUE THREAD

**Issue by PhantomPhixer** [mvdbent/CIS-Script#16]
In the script items 5.1.7 and 5.1.8 relate to world writable files.
in the custom schema these are items 5.1.3 and 5.1.4

**Comment by chrisleduc** [comment]
I found that the sample json file provided is not up to date at all. You should instead run:
`Assemble.sh -j` which will create the Custom Schema based on the fragments and make sure it is always 100% accurate.

Do not use the current pre-compiled json file as it has many many more issues than just this one.
