### ISSUE TITLE
Custom Schema 5.2.1 5.2.2 etc missing?

### ISSUE THREAD

**Issue by mat-griffin** [mvdbent/CIS-Script#17]
The custom schema goes from 5_18 to 6_1_1
All the password items etc like 5.2.1, 5.2.2 etc are missing? This on purpose?

```
        "OrgScore5_18": {
            "type": "boolean",
            "title": "5.18 System Integrity Protection status (Automated)",
            "description": "This boolean is true or false.",
            "default": "false"
        },
        "OrgScore6_1_1": {
            "type": "boolean",
            "title": "6.1.1 Display login window as name and password (Automated)",
            "description": "This boolean is true or false.",
            "default": "false"
        },
```

https://github.com/mvdbent/CIS-Script/blob/dev/Jamf/Jamf%20Pro%20Custom%20Schema.json

**Comment by chrisleduc** [comment]
I found that the sample json file provided is not up to date at all. You should instead run:
`Assemble.sh -j` which will create the Custom Schema based on the fragments and make sure it is always 100% accurate.

Do not use the current pre-compiled json file as it has many many more issues than just this one.

**Comment by mvdbent** [comment]
next time, will make sure that the example code is uptodate
