### ISSUE TITLE
5.13 down as login banner when it should be login window text

### ISSUE THREAD

**Issue by tkimpton** [mvdbent/CIS-Script#19]
5.13 is incorrect and shouldnt be checking for a banner. This should actually be "create a custom	message	for the Login Screen"

sudo defaults read /Library/Preferences/com.apple.loginwindow.plist 
LoginwindowText

**Comment by chrisleduc** [comment]
I found that the sample json file provided is not up to date at all. In your case it seems to me that the Fragment is correct but the json file is not. You should instead run:
`Assemble.sh -j` which will create the Custom Schema based on the fragments and make sure it is always 100% accurate.

Do not use the current pre-compiled json file as it has many many more issues than just this one.
