### ISSUE TITLE
5.13 Is not showing up in the within the JSON file

### ISSUE THREAD

**Issue by motionbug** [mvdbent/CIS-Script#21]
There is an issue within the fragment when building out the JSON file there is no 5.13 within the build. So without a value set that script will run all the time even if we are not checking for level 2

**Comment by chrisleduc** [comment]
I found that the sample json file provided is not up to date at all. You should instead run:
`Assemble.sh -j` which will create the Custom Schema based on the fragments and make sure it is always 100% accurate.

Do not use the current pre-compiled json file as it has many many more issues than just this one.

**Comment by mvdbent** [comment]
Issue is resolved thnx @chrisleduc
