### ISSUE TITLE
Useless use of cat

### ISSUE THREAD

**Issue by mikaellofgren** [mvdbent/CIS-Script#3]
Thanks for all, started to use some for CIS, did run a shellcheck.net check and it complained about "Useless use of cat"
https://github.com/koalaman/shellcheck/wiki/SC2002

https://github.com/mvdbent/CIS-Script/blob/abc852aae8dbec71004b66860536e9c9c8478840/Fragments/OrgScores/OrgScore3_4.sh#L29

Can be changed to
`oldExpireAfter=$( grep -E  "expire-after" /etc/security/audit_control )`

Thanks!

**Comment by mvdbent** [comment]
Thnx for the find @mikaellofgren
